#!/usr/bin/bash
set -x
ls /app/lib/kernels
ls /app/lib/kernels/linux-5-18-2
#KERNEL_VERSION=5.18.2
#mkdir -p ~/kernel
#cp /app/bin/linux ~/kernel/linux-setup
#cp -r /app/kernel/linux-$KERNEL_VERSION ~/kernel/linux-$KERNEL_VERSION
#cd ~
#HOME=$(pwd)
#flatpak-spawn --host pkexec $HOME/kernel/linux-setup $HOME $KERNEL_VERSION